# Generated by Django 4.1.7 on 2023-06-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_equipment_order_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='serial_key',
            field=models.CharField(default=1312312, max_length=128),
            preserve_default=False,
        ),
    ]
