# Generated by Django 4.1.7 on 2023-04-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_role_client_alter_order_client_alter_order_cook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент'},
        ),
    ]
