# Generated by Django 4.1.7 on 2023-04-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
