# Generated by Django 4.1.7 on 2023-04-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(auto_created=True, default="2000-02-02"),
            preserve_default=False,
        ),
    ]
