# Generated by Django 4.1.7 on 2023-04-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_alter_order_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(null=True, to='restaurant_app.drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(null=True, to='restaurant_app.food'),
        ),
    ]
