# Generated by Django 4.1.7 on 2023-04-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_remove_order_drink_remove_order_food_order_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(to='restaurant_app.drink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='restaurant_app.food'),
        ),
    ]
