# Generated by Django 4.1.7 on 2023-04-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0009_alter_order_drink_alter_order_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='order',
            field=models.ManyToManyField(related_name='order_drink', to='restaurant_app.order'),
        ),
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.ManyToManyField(related_name='order_food', to='restaurant_app.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(related_name='drink_order', to='restaurant_app.drink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(related_name='food_order', to='restaurant_app.food'),
        ),
    ]
