# Generated by Django 4.1.7 on 2023-04-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_drink_order_food_order_alter_order_drink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='order',
        ),
        migrations.RemoveField(
            model_name='food',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drink_order', to='restaurant_app.drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_order', to='restaurant_app.food'),
            preserve_default=False,
        ),
    ]
