# Generated by Django 4.1.7 on 2023-04-13 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0012_alter_order_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vip', models.BooleanField(blank=True, null=True)),
                ('is_engaged', models.BooleanField(default=False)),
                ('is_for_children', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.place')),
            ],
        ),
    ]
